### ISSUE TITLE
1.2 Ca manque de couleurs!

### ISSUE THREAD

**Issue by Dok-T** [KiWindows/pve-init#3]
plus de couleurs sur le menu :(

**Comment by KiWindows** [comment]
OUI c’est NORMAL je ne l’ai toujours pas implémenté > :c
Ça viendras p-e demain, dans le sens ou j’essaie déjà de mettre tous mes containers (notamment mon container web) en clé SSH (histoire de sécuriser le bordel), puis je vais implémenter le logo que tu m’as refais 😊

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : DokT<mailto:notifications@github.com>
Envoyé le :lundi 1 juin 2020 00:34
À : KiWindows/pve-autofree<mailto:pve-autofree@noreply.github.com>
Cc : Subscribed<mailto:subscribed@noreply.github.com>
Objet :[KiWindows/pve-autofree] 1.2 Ca manque de couleurs! (#3)


plus de couleurs sur le menu :(
